services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=library_db'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data


  app:
      build: .
      ports:
        - "8081:8080"
      depends_on:
        - postgres
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 12345

volumes:
    db-data: